### ISSUE TITLE
spotidl fails to work thrwing ffmpeg not installed error

### ISSUE THREAD

**Issue by iseeghosts** [dhruv-ahuja/spoti-dl#1]
Gettig ffmpeg not installed error even if I have set the path to ffmpeg and the command prompt does have output for ffmpeg command
![image](https://user-images.githubusercontent.com/34771316/155184985-847b6030-e5c6-48f6-80d5-35f3b1f8763c.png)

I've also installed ffmpeg-python, ffmpeg, python-ffmpeg through pip but neither of these are working

**Comment by dhruv-ahuja** [comment]
Hey, thanks for opening the issue. I'll try some stuff out tomorrow and get back to you.

**Comment by dhruv-ahuja** [comment]
@iseeghosts hello, please try uninstalling the current spoti-dl package from pip and try using this version
`pip install -i https://test.pypi.org/simple/ spoti-dl`
and tell me whether that works for you now, since it is working on my windows computer

**Comment by dhruv-ahuja** [comment]
Please re-install the official pip package or update to version 1.0.1 as that fixes this bug. @iseeghosts

**Comment by iseeghosts** [comment]
nvm, it worked, I forot to add the scripts directory in path
