### ISSUE TITLE
How do I download the file with different bitrate or format?

### ISSUE THREAD

**Issue by iseeghosts** [dhruv-ahuja/spoti-dl#2]
What arguments do I input to download mp3 or flac and the bitrates?

**Comment by dhruv-ahuja** [comment]
hey, thanks for making this issue. I have added all argument flags you can use in the app in the readme file now. You can check the readme file [here](https://github.com/dhruv-ahuja/spoti-dl/blob/home/README.md). 
the issue was fixed in aebe3753fe9089671ce4e4019fad922caf62d2c4
