### ISSUE TITLE
How to install it please

### ISSUE THREAD

**Issue by Mojas84** [dhruv-ahuja/spoti-dl#5]
Hi i basic PC user. I install python 3.11. Download source. On powershell pip install spoti-dl but not work.....

**Comment by rusocop** [comment]
### Im using Windows 10

# 1 Install python from Microsoft Store. Version 3.8 is okay.

# 2 Install ffmpeg. How? Windows users can download FFMPEG pre-built binaries from (http://ffmpeg.zeranoe.com/builds/). Extract the file using 7-zip or WinRar to a foldrer and [add the folder to your PATH environment variable](http://www.wikihow.com/Install-FFmpeg-on-Windows)

# 3 Open CMD and install spoti-dl writing **_pip install spoti-dl_**

# 4 Do the Spotify Dev thing
Go to Spotify Dev Dashboard (https://developer.spotify.com/dashboard/applications)
Login with your credentials and click on "create an app".
Enter any name of choice, app description, tick the checkbox and proceed.
Now you have access to your client ID. Click on "Show client secret" to get your client secret. Save the numbers somewhere for you to copy them after.
From here, click on "edit settings" and in the "redirect URIs" section add any localhost URL. Use: http://localhost:8080/callback

# 5 Now with the numbers saved do this one by one in the CMD (DO NOT CLOSE IT, if you close it you have to write it again):
set SPOTIPY_CLIENT_ID=_your ID_
set SPOTIPY_CLIENT_SECRET=_your secret ID_
set SPOTIPY_REDIRECT_URI=http://localhost:8080/callback

# 6 **If you want to see if your installation was correct do this:**
- Click Windows+R and write %appdata%
- Click enter
- It will open "C:\Users\user\AppData\Roaming"
- But you have to go here -> **C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts**
- Find "spotidl" there. If you have it, it's all OK!

# 7 SO NOW THE ACTION OF DOWNLOAD THINGS (dont forget to change "user" in the line xd):
In the CMD put the "spotidl" path in the line (see above how to find it):
For example:
**C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\spotidl -c flac LINK**
It will download the flac version of the song (about 10mb/minute of song depending on genre of course)

The song will be saved in C:\Users\user\dl\

**Comment by dhruv-ahuja** [comment]
hi, installation on Windows is a can of worms in and itself, with a bunch of different problems most times. I hope that the above answer had helped you out, as I will not be covering individual problem cases.
I hope you understand.
