### ISSUE TITLE
(Feature request) Add track order numbers for album downloads

### ISSUE THREAD

**Issue by kenwaytis** [dhruv-ahuja/spoti-dl#8]
Hello! Thank you very much for your excellent work; it has helped me solve the problem of digitizing albums after purchasing them. I have another feature request, which might not be difficult for the entire program given that it already fetches Spotify song metadata.

Feature request:
(Optional) When downloading an album, automatically prepend track order numbers (01, 02, ...) to the song titles.

This would greatly reduce the time I spend manually adding information on devices that do not support metadata.

**Comment by dhruv-ahuja** [comment]
Hey! Thank you very much for your kind words, I'm glad you find my app useful 🤠

Yeah sure that should be doable. I'll try and work on this sometime. Won't probably be possible before this, most likely the next weekend though.

**Comment by kenwaytis** [comment]
Greetings!

I've also discovered another issue: no matter what bitrate (-b) I specify or even if I use 'best', the downloaded audio quality is always 128kbps. I've tested this across many albums and it's the same.

Is this because only paid Youtube Music accounts have access to high-quality audio downloads?

**Comment by dhruv-ahuja** [comment]
Oh I see. Yeah that makes sense. 
I'll look into this at a future date to see if something can be done regarding this.

**Comment by dhruv-ahuja** [comment]
Hey @kenwaytis! I've added this feature to the app. Will publish a new version in due time (hopefully) containing this and a few improvements that I've in mind.

**Comment by kenwaytis** [comment]
> Hey @kenwaytis! I've added this feature to the app. Will publish a new version in due time (hopefully) containing this and a few improvements that I've in mind.

Awesome, thanks Dhruv! Really appreciate the quick turn-around. Looking forward to the new version with the added features. Keep up the good work! 🎉

**Comment by dhruv-ahuja** [comment]
Hey, changes are live. You can now use the `-t` flag to add track order to your output files. Please update the app to version 2.1.1 :D
